from core.models import Question
questions = [
    "Examine my inner world",
    "Understand my emotions",
    "Explore my inner self",
    "Identify my motivations",
    "Know myself thoroughly",
    "Observe my reactions",
    "Know who I really am",
    "Discover my strengths",
    "Scan my unconscious",
    "Analyze my feelings",
    "Interpret my behaviour",
    "Notice subtle gestures",
    "Read people’s minds",
    "Decode body language",
    "Guess intimate secrets",
    "Interpret a long silence",
    "Sense things unsaid",
    "Have a keen intuition",
    "Analyze facial features",
    "Capture an  innuendo",
    "Grasp people’s motives",
    "Detect people’s moods",
    "Wonder about afterlife",
    "Gaze at the Universe",
    "Ponder the meaning of life",
    "Be one with nature",
    "Pray in absolute silence",
    "Meditate every day",
    "Enrich my spiritual life",
    "Practice meditation",
    "Cultivate my innerness",
    "Connect with the cosmos",
    "Deepen my faith",
    "Play to be winner",
    "Break a new record",
    "Win a competition",
    "Win first place",
    "Reach the very top",
    "Strive for success",
    "Have ambition",
    "Always outdo myself",
    "Succeed at all costs",
    "Always aim higher",
    "Seek excellence",
    "Become very popular",
    "Show pride in myself",
    "Be worthy of admiration",
    "Stand out socially",
    "Deserve great praise",
    "Be greatly appreciated",
    "Make a good impression",
    "Receive compliments",
    "Gain great prestige",
    "Strongly aspire to fame                                     ",
    "Enhance my reputation",
    "Exercise leadership",
    "Have great power",
    "Give clear orders",
    "Maintain command",
    "Give instructions",
    "Exert strong influence",
    "Have leadership skills",
    "Be obeyed promptly",
    "Be quite authoritarian",
    "Give sound advice",
    "Supervise subordinates",
    "Have easy speech",
    "Chat with strangers ",
    "Start a conversation",
    "Converse with others",
    "Speak very often",
    "Talk for a long time",
    "Have long discussions ",
    "Communicate orally   ",
    "Talk about everything",
    "Engage in a dialogue",
    "Chat around the fire",
    "Join an association",
    "Be a member of a club",
    "Form a united group",
    "Mingle with a crowd",
    "Develop camaraderie",
    "Seek out company",
    "Establish friendships",
    "Meet many people",
    "Belong to a group",
    "Be really sociable",
    "Socialize with others",
    "Work with a partner",
    "Offer my collaboration",
    "Share a common goal",
    "Cooperate with others",
    "Integrate into society",
    "Act by mutual consent",
    "Express my solidarity ",
    "Foster mutual help",
    "Cowork in a team",
    "Share an objective",
    "Interact with others",
    "Count only on myself",
    "Work without support",
    "Manage without help",
    "Protect my autonomy",
    "Be self-supporting",
    "Do without others",
    "Make it by myself",
    "Make my own decisions",
    "Owe nothing to anyone",
    "Maintain self-sufficiency",
    "Stand on my own feet",
    "Enjoy total freedom",
    "Always do as I please",
    "Have freedom at heart",
    "Have freedom of action",
    "Feel free as a bird",
    "Live my life as I fancy",
    "Be free from duties",
    "Do anything I feel like",
    "Have free rein",
    "Enjoy my liberty",
    "Live without restraint",
    "Lead a solitary life",
    "Stay on the outside",
    "Live like a hermit",
    "Avoid public places",
    "Live in isolation",
    "Always stay behind  ",
    "Stay in my cocoun",
    "Delimit my territory",
    "Keep my distance",
    "Protect my privacy ",
    "Limit my friendships",
    "Have a lot of fun",
    "Have a fabulous time",
    "Party quite frequently",
    "Play to amuse myself",
    "Bite eagerly into life",
    "Enjoy exciting leisure",
    "Seek distractions",
    "Enjoy a great feast",
    "Take a long vacatiion",
    "Truly be fun-loving ",
    "Party without limit",
    "Find sexual fulfillment",
    "Enjoy erotic pleasure",
    "Express my sexuality",
    "Feel a fiery passion",
    "Flourish sexually",
    "Dream of hot love",
    "Satisfy my libido",
    "Flirt and seduce",
    "Give sensual kisses",
    "Savour eroticism",
    "Fantasize sensually",
    "Tell funny stories",
    "Play tricks often",
    "Tell good jokes",
    "Provoke laughter",
    "Tease my friends",
    "Laugh out loud",
    "Always clown around",
    "Practise self-derision",
    "Make practical jokes",
    "Make people laugh",
    "Crack a funny joke",
    "Tidy up my things",
    "Always be orderly",
    "Clean my room",
    "Do a major cleaning",
    "Put things in order",
    "Feel like tidying up ",
    "Clean thoroughly",
    "Clean up a mess",
    "Organize a drawer",
    "Classify objects",
    "Put away utensils",
    "Always plan my day",
    "Prepare a work plan",
    "Stick to an agenda",
    "Organize my activities",
    "Schedule an activity",
    "Foresee everything",
    "Develop a strategy",
    "Work methodically",
    "Always be prepared",
    "Organize a program",
    "Prepare a schedule",
    "Be a perfectionist",
    "Be very meticulous",
    "Fine-tune each work",
    "Check minute details",
    "Work with great care",
    "Work meticulously",
    "Verify and reverify",
    "Correct deficiencies",
    "Notice any defect",
    "Pay attention to details",
    "Worry about precision",
    "Invent something new",
    "Initiate a novel project",
    "Create an original work",
    "Devise a special gadget",
    "Make a great discovery",
    "Have a creative spirit",
    "Be at the leading edge",
    "Daydream creatively",
    "Innovate brilliantly",
    "Always renew myself",
    "Invent abundantly",
    "Grasp theoretical ideas",
    "Analyze abstract ideas",
    "Interpret a symbol",
    "Develop concepts",
    "Be able to theorize",
    "Reformulate concepts",
    "Propose clear concepts",
    "Study abstract systems",
    "Explore a theory",
    "Decode abstractions",
    "Resort to abstraction",
    "Reflect about mankind",
    "Read great thinkers",
    "Think profoundly",
    "Weigh up an idea",
    "Think hard and long",
    "Analyze different ideas",
    "Admire philosophers",
    "Ask myself questions",
    "Outline my thinking",
    "Learn how to reflect",
    "Investigate an issue  ",
    "Obey established rules",
    "Abide by guidelines",
    "Follow each instruction",
    "Respect any authority",
    "Follow the mainstream",
    "Advocate for conformity",
    "Observe conventions",
    "Submit to fulfill orders",
    "Act like the majority",
    "Imitate my neighbours",
    "Banish originality",
    "Safeguard traditions",
    "Stick to old values",
    "Respect old customs",
    "Stay true to the past",
    "Evoke the old days",
    "Keep track of the past",
    "Follow traditional rites",
    "Practise ancient rituals",
    "Praise traditionalism",
    "Pass down values",
    "Honour ancestors",
    "Look for my safety",
    "Ask for protection",
    "Feel very secure",
    "Live in total safety",
    "Be well protected",
    "Be safe from danger",
    "Find solid protection",
    "Avoid any mishap",
    "Be safe from threats",
    "Look for safeness",
    "Always avoid danger",
    "Volunteer my services",
    "Give willingly of myself",
    "Have a heart of gold",
    "Lend a hand often",
    "Help the needy",
    "Comfort the afflicted",
    "Give some of my time",
    "Be sensitive to misery",
    "Show my generosity",
    "Alleviate suffering",
    "Sacrifice willingly",
    "Avoid painful quarrels",
    "Prevent bitter conflicts",
    "Get along with others",
    "Seek sweet harmony",
    "Make peace willingly",
    "Live in total peace",
    "Show great tolerance",
    "Have a peaceful spirit",
    "Adopt compromises",
    "Live without conflict",
    "Endure in silence",
    "Show great respect",
    "Let people speak",
    "Listen very carefully",
    "Greet everybody",
    "Be tactful in society",
    "Be extremely polite",
    "Show consideration",
    "Be aware of others",
    "Be very respectful",
    "Admire old people",
    "Respect etiquette",
    "Reply to insults",
    "Retort if provoked",
    "Be quick on the draw",
    "Give a scathing reply",
    "Respond tit for tat",
    "Humble a boaster",
    "Shut up a braggart",
    "Respond at once",
    "Interrupt a chatterer",
    "Retort tooth and nail",
    "Retort very promptly",
    "Take ruthless reprisal",
    "Retaliate harshly",
    "Settle accounts coldly",
    "Hold a grudge",
    "Avenge a grave insult",
    "Remember an affront",
    "Have strong grievances",
    "Plot harsh revenge",
    "Withold forgiveness",
    "Maintain resentment",
    "Take hard revenge",
    "Vent my frustration",
    "Let my anger out",
    "Express my irritation",
    "Get angry if necessary",
    "Voice my annoyance",
    "Be vocally aggressive",
    "Lose my temper",
    "Fly into a rage",
    "Throw a tantrum",
    "Chafe for no reason",
    "Be furious sometimes",
    "Face the worst dangers",
    "Be a real daredevil",
    "Face daring challenges",
    "Really risk a lot",
    "Take wild risks",
    "Be foolishly reckless",
    "Be afraid of nothing",
    "Often play with fire",
    "Display recklessness",
    "Flirt with danger",
    "Brave a threat",
    "Embark on adventure",
    "Leap into the unknown",
    "Visit exotic countries",
    "Become a globetrotter",
    "Travel over the world",
    "Take a very long trip",
    "Explore new horizons",
    "Be very adventurous",
    "Often go abroad",
    "Go off to explore ",
    "Venture far away",
    "Modify my projects",
    "Avoid boring routines",
    "Break the monotony",
    "Diversify my activities",
    "Change my mind often",
    "Look for sheer variety",
    "Welcome change",
    "Get out for a change ",
    "Give up a dull routine",
    "Try different activities",
    "Change my activities ",
    "Display intense joy",
    "Be very enthusiastic",
    "Express my joviality",
    "Be overtly cheerful",
    "Express my jubilation",
    "Be in a joyful mood",
    "Release exuberance ",
    "Have a cheerful heart",
    "Have outbursts of joy",
    "Look overjoyed",
    "Feel enjoyment",
    "Have sparkling vitality",
    "Be quite full of energy",
    "Express my liveliness",
    "Be the lively type",
    "Burst with dynamism",
    "Sparkle with life",
    "Radiate my inner fire",
    "Display great vigor",
    "Explode with energy",
    "Be remarkably alert",
    "Live with intensity",
    "Show my love of life",
    "Display optimism",
    "Radiate happiness",
    "Be born for happiness",
    "Be in a good mood ",
    "Always trust in life",
    "Bask in serenity",
    "Have positive views",
    "Be extremely happy",
    "Live optimistically",
    "Have a fulfilled life",

]

print(len(questions))

for i in range(0, len(questions)):
    # print(questions[i])
    j = 1
    j = int(i / 11)
    question = Question(question=questions[i], subscale=str(j+1))
    question.save()
