# Generated by Django 2.2.13 on 2021-01-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='index',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='subscale',
            field=models.CharField(choices=[('1', 'SELF-ANALYSIS'), ('2', 'INTUITION'), ('3', 'MEDITATION'), ('4', 'AMBITION'), ('5', 'PRIDE'), ('6', 'LEADERSHIP'), ('7', 'CONVERSATION'), ('8', 'AFFILIATION'), ('9', 'SOLIDARITY'), ('10', 'AUTONOMY'), ('11', 'FREEDOM'), ('12', 'SOLITUDE'), ('13', 'AMUSEMENT'), ('14', 'EROTICISM'), ('15', 'PLAYFULNESS'), ('16', 'ORDERLINESS'), ('17', 'PLANNING'), ('18', 'PRECISION'), ('19', 'INNOVATION'), ('20', 'ABSTRACTION'), ('21', 'REFLECTION'), ('22', 'CONFORMITY'), ('23', 'TRADITION'), ('24', 'SECURITY'), ('25', 'DEVOTION'), ('26', 'HARMONY'), ('27', 'RESPECT'), ('28', 'RESPONSE'), ('29', 'REVENGE'), ('30', 'ANGER'), ('31', 'TEMERITY'), ('32', 'ADVENTURE'), ('33', 'VARIETY'), ('34', 'JOVIALITY'), ('35', 'VIVACITY'), ('36', 'OPTIMISM')], max_length=1, null=True),
        ),
    ]
